ersion: 2
updates:
  - package-ecosystem: "npm" # Busca actualizaciones en package.json
    directory: "/"           # En la carpeta raíz
    schedule:
      interval: "daily"      # Revisa si hay versiones nuevas cada día
